COLORS = ['rx', 'yx', 'bx', 'mx', 'cx',
          'ro', 'yo', 'bo', 'mo', 'co',
          'rv', 'yv', 'bv', 'mv', 'cv',
          'r^', 'y^', 'b^', 'm^', 'c^',
          'r<', 'y<', 'b<', 'm<', 'c<',
          'r>', 'y>', 'b>', 'm>', 'c>',
          'r3', 'y3', 'b3', 'm3', 'c3',
          'r4', 'y4', 'b4', 'm4', 'c4',
          'rs', 'ys', 'bs', 'ms', 'cs',
          'rp', 'yp', 'bp', 'mp', 'cp',
          'rh', 'yh', 'bh', 'mh', 'ch',
          'r1', 'y1', 'b1', 'm1', 'c1',
          'r2', 'y2', 'b2', 'm2', 'c2']
